Removed Backup Process

diff --git a/.github/workflows/flyway-migrations.yml b/.github/workflows/flyway-migrations.yml
--- a/.github/workflows/flyway-migrations.yml
+++ b/.github/workflows/flyway-migrations.yml
@@ -101,38 +101,38 @@ jobs:
       #   shell: powershell
 
       # - name: Backup Database
-        run: |
-          echo "Checking if the database exists before backup..."
+      #   run: |
+      #     echo "Checking if the database exists before backup..."
 
-          # Check if the database exists
-          $dbExists = sqlcmd -S 192.168.4.37,1433 -U $Env:DB_USER -P $Env:DB_PASSWORD -Q "IF EXISTS (SELECT name FROM sys.databases WHERE name = 'ArgaamScreener_DEV') PRINT 'DatabaseExists'" -h -1
+      #     # Check if the database exists
+      #     $dbExists = sqlcmd -S 192.168.4.37,1433 -U $Env:DB_USER -P $Env:DB_PASSWORD -Q "IF EXISTS (SELECT name FROM sys.databases WHERE name = 'ArgaamScreener_DEV') PRINT 'DatabaseExists'" -h -1
 
-          if ($dbExists -match "DatabaseExists") {
-            echo "Database exists. Proceeding with backup..."
-            $timestamp = Get-Date -Format "yyyyMMdd_HHmmss"
-            $backupFile = "C:\backups\ArgaamScreener_DEV_$timestamp.bak"
+      #     if ($dbExists -match "DatabaseExists") {
+      #       echo "Database exists. Proceeding with backup..."
+      #       $timestamp = Get-Date -Format "yyyyMMdd_HHmmss"
+      #       $backupFile = "C:\backups\ArgaamScreener_DEV_$timestamp.bak"
 
-            # Ensure backup directory exists
-            if (-not (Test-Path "C:\backups")) {
-              New-Item -Path "C:\backups" -ItemType Directory
-            }
+      #       # Ensure backup directory exists
+      #       if (-not (Test-Path "C:\backups")) {
+      #         New-Item -Path "C:\backups" -ItemType Directory
+      #       }
 
-            # Run SQLCMD to back up the database
-            sqlcmd -S 192.168.4.37,1433 -U $Env:DB_USER -P $Env:DB_PASSWORD -Q "BACKUP DATABASE [ArgaamScreener_DEV] TO DISK = '$backupFile' WITH FORMAT, INIT, NAME = 'ArgaamScreener_DEV-Full Database Backup';"
+      #       # Run SQLCMD to back up the database
+      #       sqlcmd -S 192.168.4.37,1433 -U $Env:DB_USER -P $Env:DB_PASSWORD -Q "BACKUP DATABASE [ArgaamScreener_DEV] TO DISK = '$backupFile' WITH FORMAT, INIT, NAME = 'ArgaamScreener_DEV-Full Database Backup';"
 
-            if (Test-Path $backupFile) {
-              echo "Backup successful: $backupFile"
-            } else {
-              echo "Database backup failed!"
-              exit 1
-            }
-          } else {
-            echo "Database does not exist. Skipping backup."
-          }
-        shell: powershell
-        env:
-          DB_USER: ${{ secrets.DB_USER }}
-          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
+      #       if (Test-Path $backupFile) {
+      #         echo "Backup successful: $backupFile"
+      #       } else {
+      #         echo "Database backup failed!"
+      #         exit 1
+      #       }
+      #     } else {
+      #       echo "Database does not exist. Skipping backup."
+      #     }
+      #   shell: powershell
+      #   env:
+      #     DB_USER: ${{ secrets.DB_USER }}
+      #     DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
 
       # Run Flyway Repair
       - name: Run Flyway Repair
